version: '3.8'
services:
  postgres:
    image: postgres:12-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: webspajz
      POSTGRES_PASSWORD: webspajz
    volumes:
      - pg:/var/lib/postgresql/data

volumes:
  pg: