spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/webspajz
    username: webspajz
    password: webspajz
    platform: postgresql
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    properties:
      hibernate:
        default_schema: public
  flyway:
    locations: classpath:db
